replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /counter
  hosts:
    - host: localhost
      paths:
        - path: /counter
          pathType: Prefix
  tls: []

secret:
  password: MYPASSWORD